apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: dev-ops-project
  labels:
    app: flask-app #?
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
                 