apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: dev-ops-project
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts: 
        - name: nginx-cm
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-cm
        configMap:
          name: nginx-cm